{
 "title": "MYAPP DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket{outcome=\"SUCCESS\"}[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{outcome=\"SUCCESS\"}[2m]))) * 1000"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_requests_seconds_bucket{outcome=\"SUCCESS\"}[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency 0.99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_requests_seconds_bucket{outcome=\"SUCCESS\"}[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency 0.95",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket{outcome=\"SUCCESS\"}[2m]))) * 1000"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Latency 0.5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_requests_seconds_bucket{}[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(http_server_requests_seconds_count{status != \"500\"}[2m]))"
    },
    {
     "expr": "sum by (exported_endpoint) (rate(http_server_requests_seconds_count{status = \"500\"}[2m]))"
    }
   ]
  }
 ]
}