apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: otus-app-virtual-service
spec:
  hosts:
    - arch.homework
  http:
    - route:
        - destination:
            host: arch.homework
            subset: v1
          weight: 50
        - destination:
            host: arch.homework
            subset: v2
          weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: otus-app-dest-rule
spec:
  host: arch.homework
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
